/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MechanicsRouteImport } from './routes/mechanics'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as DhabaRouteImport } from './routes/dhaba'
import { Route as IndexRouteImport } from './routes/index'

const MechanicsRoute = MechanicsRouteImport.update({
  id: '/mechanics',
  path: '/mechanics',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const DhabaRoute = DhabaRouteImport.update({
  id: '/dhaba',
  path: '/dhaba',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dhaba': typeof DhabaRoute
  '/drivers': typeof DriversRoute
  '/fleet': typeof FleetRoute
  '/mechanics': typeof MechanicsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dhaba': typeof DhabaRoute
  '/drivers': typeof DriversRoute
  '/fleet': typeof FleetRoute
  '/mechanics': typeof MechanicsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dhaba': typeof DhabaRoute
  '/drivers': typeof DriversRoute
  '/fleet': typeof FleetRoute
  '/mechanics': typeof MechanicsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dhaba' | '/drivers' | '/fleet' | '/mechanics'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dhaba' | '/drivers' | '/fleet' | '/mechanics'
  id: '__root__' | '/' | '/dhaba' | '/drivers' | '/fleet' | '/mechanics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DhabaRoute: typeof DhabaRoute
  DriversRoute: typeof DriversRoute
  FleetRoute: typeof FleetRoute
  MechanicsRoute: typeof MechanicsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mechanics': {
      id: '/mechanics'
      path: '/mechanics'
      fullPath: '/mechanics'
      preLoaderRoute: typeof MechanicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dhaba': {
      id: '/dhaba'
      path: '/dhaba'
      fullPath: '/dhaba'
      preLoaderRoute: typeof DhabaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DhabaRoute: DhabaRoute,
  DriversRoute: DriversRoute,
  FleetRoute: FleetRoute,
  MechanicsRoute: MechanicsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
